version: 2

sources:
  - name: br_me_comex_stat
    database: basedosdados
    schema: br_me_comex_stat
    tables:
      - name: municipio_exportacao
      - name: municipio_importacao
      - name: dicionario

  - name: br_bd_diretorios_brasil
    database: basedosdados
    schema: br_bd_diretorios_brasil
    tables:
      - name: municipio

  - name: br_bd_diretorios_mundo
    database: basedosdados
    schema: br_bd_diretorios_mundo
    tables:
      - name: sistema_harmonizado